name: adopt_me
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.2.3
  confetti: ^0.8.0
  cached_network_image: ^3.4.0
  photo_view: ^0.15.0
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  flutter_lints: ^3.0.0
  bloc_test:
  test: any
flutter_icons:
  android: true
  ios: true
  image_path: "assets/aisensyofficial_logo.jpeg"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pets.json
    - assets/
